services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Android_form.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Android_form.settings