# Generated by Django 5.2.1 on 2025-05-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='education',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='names',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='sports',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
