# Generated by Django 5.2.1 on 2025-05-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_student_education_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
